name: ourchat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  web_socket_channel: ^3.0.3
  crypto: ^3.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  logger: ^2.4.0
  protobuf: ^4.0.0
  grpc: ^4.0.1
  fixnum: ^1.1.1
  path_provider: ^2.1.5
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  shared_preferences: ^2.5.3

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
