name: ourchat
description: "A chat application"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  intl: any
  logger: ^2.4.0
  protobuf: ^5.1.0
  grpc: ^5.0.0
  fixnum: ^1.1.1
  path_provider: ^2.1.5
  drift: ^2.30.0
  drift_flutter: ^0.2.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  image_picker: ^1.2.0
  hashlib: ^2.2.0
  cached_network_image: ^3.4.1
  window_manager: ^0.5.1
  tray_manager: ^0.5.1
  # wait for PR
  # flutter_markdown_plus: ^1.0.5
  flutter_markdown_plus:
    git:
      url: git@github.com:senlinjun/flutter_markdown_plus.git
      ref: noScroll
  markdown: ^7.3.0
  sqlite3: ^2.9.4 # Required for drift on Web
  http: ^1.2.2
  # wait for PR
  # ota_update: ^7.1.0
  ota_update:
    git:
      url: git@github.com:senlinjun/ota_update.git
      ref: desktop_dev
  device_info_plus: ^12.3.0
  flutter_cache_manager: ^3.4.1
  image_compression: ^1.0.5
  mime: ^1.0.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.30.0
  build_runner: ^2.4.15
  build_web_compilers: ^4.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - web/sqlite3.wasm
    - web/drift_worker.js
    - web/drift_worker.min.js
